# Generated by Django 3.2.6 on 2021-08-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
