# Generated by Django 3.2.6 on 2021-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='static/posts/%Y/%m'),
        ),
    ]
