# Generated by Django 3.2.6 on 2021-10-15 13:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0011_auto_20210927_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('travel_schedule', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='introduction',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='note',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='service',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.DeleteModel(
            name='TourDetail',
        ),
        migrations.AddField(
            model_name='tourschedules',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_detail_tour', to='TravelMS.tour'),
        ),
    ]
