# Generated by Django 3.2.6 on 2021-10-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0013_auto_20211015_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
