# Generated by Django 3.2.6 on 2021-12-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0014_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('tour', 'user')},
        ),
    ]
