# Generated by Django 3.2.6 on 2021-12-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0017_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='priceAdult',
        ),
        migrations.AddField(
            model_name='booking',
            name='day_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='day_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='priceChildren',
            field=models.BigIntegerField(null=True),
        ),
    ]
