# Generated by Django 3.2.6 on 2021-12-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelMS', '0018_auto_20211224_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day_start',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priceAdult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='priceChildren',
        ),
    ]
